#!/bin/bash

ls ~/.config/scripts/colorscript |sort -R |tail -1 |while read file; do
    # Something involving $file, or you can leave
    # off the while to just get the filenames
	exec "~/.config/scripts/colorscript/$file"
done
